name: "SAG Helm deploy action"

inputs:
  release-name:
    required: true
    description: ""
  helm-chart:
    required: true
    description: ""
  docker-registry:
    required: true
    description: ""
  docker-username:
    required: true
    description: ""
  docker-password:
    required: true
    description: ""

runs:
  using: "composite"
  steps:

    - name: Helm deploy
      shell: bash
      run: |
          kubectl create secret docker-registry regcred --docker-server=${{ inputs.docker-registry }} --docker-username=${{ inputs.docker-username }} --docker-password=${{ inputs.docker-password }} || true
          helm upgrade ${{ inputs.release-name }} --install ${{ inputs.helm-chart }} ${{ inputs.extra-args }}
          helm get ${{ inputs.release-name }} >> $GITHUB_STEP_SUMMARY